[private_config]
consensus_public_key = "8b2366d0352d82cf6f764d20d934ab839c4d5b7ff839b9ed07b1ae8ce47712aa"
external_address = "127.0.0.1:7092"
listen_address = "0.0.0.0:7092"
master_key_path = "master.key.toml"

[private_config.api]
private_api_address = "0.0.0.0:9004"
public_api_address = "0.0.0.0:9001"
state_update_timeout = 10000

[private_config.api.server_restart]
max_retries = 20
retry_timeout = 500
[[private_config.connect_list.peers]]
address = "127.0.0.1:7091"
public_key = "5a77d0421efefa232fd5e4afa95be1a253f690b48d718583df7eed8b1ceeb014"

[[private_config.connect_list.peers]]
address = "127.0.0.1:7093"
public_key = "9b5af74daee90ced86e04e5b75cc088bc5e47a9fcd65ac276bb9f0fff5bd5f63"

[private_config.database]
compression_type = "none"
create_if_missing = true
[private_config.mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[private_config.mempool.flush_pool_strategy]
timeout = 20
type = "timeout"

[private_config.network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[public_config.consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[[public_config.consensus.validator_keys]]
consensus_key = "5a77d0421efefa232fd5e4afa95be1a253f690b48d718583df7eed8b1ceeb014"
service_key = "6f650c66e05427d76686ffdaf0f2399efbf639715c8c5b61b44a7e0ca04a7342"

[[public_config.consensus.validator_keys]]
consensus_key = "8b2366d0352d82cf6f764d20d934ab839c4d5b7ff839b9ed07b1ae8ce47712aa"
service_key = "224dc2300f0186a2fc3e7168e8a6fb63b8c51702e30062f1e6968310d65fb629"

[[public_config.consensus.validator_keys]]
consensus_key = "9b5af74daee90ced86e04e5b75cc088bc5e47a9fcd65ac276bb9f0fff5bd5f63"
service_key = "755b49a66eab5dac8032b8e7589de12d7af783643ddf0a4462d422b31ce01d8e"

[public_config.general]
supervisor_mode = "simple"
validators_count = 3
