[private_config]
consensus_public_key = "2a57de61d0e5d45941aace099b8e8ac6bccfadea5e911946f464656b3e99ce70"
external_address = "127.0.0.1:7092"
listen_address = "0.0.0.0:7092"
master_key_path = "master.key.toml"

[private_config.api]
private_api_address = "0.0.0.0:9003"
public_api_address = "0.0.0.0:9001"
state_update_timeout = 10000

[private_config.api.server_restart]
max_retries = 20
retry_timeout = 500
[[private_config.connect_list.peers]]
address = "127.0.0.1:7091"
public_key = "b4b9c9d7eb91be65e4e2c05d741e8db732c15f63046d241f23791e1585b4646e"

[private_config.database]
compression_type = "none"
create_if_missing = true
[private_config.mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[private_config.mempool.flush_pool_strategy]
timeout = 20
type = "timeout"

[private_config.network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[public_config.consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[[public_config.consensus.validator_keys]]
consensus_key = "2a57de61d0e5d45941aace099b8e8ac6bccfadea5e911946f464656b3e99ce70"
service_key = "15878cb5e2278b9f9bf9eb6fdbb39b093853d80bccbee7f9f7219ccf23ce83f3"

[[public_config.consensus.validator_keys]]
consensus_key = "b4b9c9d7eb91be65e4e2c05d741e8db732c15f63046d241f23791e1585b4646e"
service_key = "ec14932a34e006b1491856b1042a0fcb68b6fa0304574cf516a221ba5d53ef29"

[public_config.general]
supervisor_mode = "simple"
validators_count = 2
