[private_config]
consensus_public_key = "e91fee16f19be4b698c5ebe3c60c389fe278113dca7a0aa67ddfe167ab6fa212"
external_address = "127.0.0.1:7092"
listen_address = "0.0.0.0:7092"
master_key_path = "master.key.toml"

[private_config.api]
private_api_address = "0.0.0.0:9003"
public_api_address = "0.0.0.0:9001"
state_update_timeout = 10000

[private_config.api.server_restart]
max_retries = 20
retry_timeout = 500
[[private_config.connect_list.peers]]
address = "127.0.0.1:7091"
public_key = "4d4fdfd5eb3fe63e790d00bb0ac2026e2fa200b5ddb5103bfc2f74de872d85fc"

[private_config.database]
compression_type = "none"
create_if_missing = true
[private_config.mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[private_config.mempool.flush_pool_strategy]
timeout = 20
type = "timeout"

[private_config.network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[public_config.consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[[public_config.consensus.validator_keys]]
consensus_key = "4d4fdfd5eb3fe63e790d00bb0ac2026e2fa200b5ddb5103bfc2f74de872d85fc"
service_key = "38fa00daa77b31e7e91d820fd89e779f362b951d4b89383cff4ea74e286b4107"

[[public_config.consensus.validator_keys]]
consensus_key = "e91fee16f19be4b698c5ebe3c60c389fe278113dca7a0aa67ddfe167ab6fa212"
service_key = "8ed6c286799877df0add75520198ef3208f810009cb72fc2d6e0c4881a901a0b"

[public_config.general]
supervisor_mode = "simple"
validators_count = 2
