address = "127.0.0.1:7092"

[consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[general]
supervisor_mode = "simple"
validators_count = 2

[validator_keys]
consensus_key = "e91fee16f19be4b698c5ebe3c60c389fe278113dca7a0aa67ddfe167ab6fa212"
service_key = "8ed6c286799877df0add75520198ef3208f810009cb72fc2d6e0c4881a901a0b"
