address = "86.190.119.237:6331"

[consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[general]
supervisor_mode = "simple"
validators_count = 2

[validator_keys]
consensus_key = "cedd949f245ed6d337fd5aee30dc693e8c32e599d00dfe9a6bdc00daa100c96b"
service_key = "32d486b5a86b3d2cc47a65b827f927b9d1d29d0da2db2df878316ffba405d9a4"
