address = "127.0.0.1:7093"

[consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[general]
supervisor_mode = "simple"
validators_count = 3

[validator_keys]
consensus_key = "9b5af74daee90ced86e04e5b75cc088bc5e47a9fcd65ac276bb9f0fff5bd5f63"
service_key = "755b49a66eab5dac8032b8e7589de12d7af783643ddf0a4462d422b31ce01d8e"
