[private_config]
consensus_public_key = "f6383e5c982600f319c9e3bf1a2230b79858697b69cc0c1fc6da5e80ebce5ad9"
external_address = "0.0.0.0:6332"
listen_address = "0.0.0.0:6332"
master_key_path = "master.key.toml"

[private_config.api]
private_api_address = "0.0.0.0:9001"
public_api_address = "0.0.0.0:9000"
state_update_timeout = 10000

[private_config.api.server_restart]
max_retries = 20
retry_timeout = 500
[[private_config.connect_list.peers]]
address = "0.0.0.0:6333"
public_key = "e4071bb12d4e494fe42afee7075110b431de1c51010c676dabb2c7909f1a681b"

[private_config.database]
compression_type = "none"
create_if_missing = true
[private_config.mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[private_config.mempool.flush_pool_strategy]
timeout = 20
type = "timeout"

[private_config.network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[public_config.consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[[public_config.consensus.validator_keys]]
consensus_key = "e4071bb12d4e494fe42afee7075110b431de1c51010c676dabb2c7909f1a681b"
service_key = "9c9369d4e130aba1ff31a9dc20429f3ce0bb27e76f5a393524a69501cecf6d76"

[[public_config.consensus.validator_keys]]
consensus_key = "f6383e5c982600f319c9e3bf1a2230b79858697b69cc0c1fc6da5e80ebce5ad9"
service_key = "10b9b74ed3d0def99547af9238283dc21f933eba3a7df773f2fcb23289183141"

[public_config.general]
supervisor_mode = "simple"
validators_count = 2
