[private_config]
consensus_public_key = "4cba4640228b65d851c0fc13f62c2d5e1bf336af6fd0a1450255b35c0656dbd2"
external_address = "94.174.127.26:6332"
listen_address = "0.0.0.0:6332"
master_key_path = "master.key.toml"

[private_config.api]
private_api_address = "0.0.0.0:9001"
public_api_address = "0.0.0.0:9000"
state_update_timeout = 10000

[private_config.api.server_restart]
max_retries = 20
retry_timeout = 500
[[private_config.connect_list.peers]]
address = "86.190.119.237:6332"
public_key = "5e4aa653da1e90a7a642e0864c36f8694d251e830755779cdfdbfe8fcd58da46"

[private_config.database]
compression_type = "none"
create_if_missing = true
[private_config.mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[private_config.mempool.flush_pool_strategy]
timeout = 20
type = "timeout"

[private_config.network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[public_config.consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[[public_config.consensus.validator_keys]]
consensus_key = "4cba4640228b65d851c0fc13f62c2d5e1bf336af6fd0a1450255b35c0656dbd2"
service_key = "12a3d4a4bbcf6ad0a7b09df87f629b99de4b69f44f004ad1ba05ad7dc77d3b2c"

[[public_config.consensus.validator_keys]]
consensus_key = "5e4aa653da1e90a7a642e0864c36f8694d251e830755779cdfdbfe8fcd58da46"
service_key = "0c9617f4ac9f94053ef1cadbbb6b7b1fb031340e9a260d5a0d93d7d22525cb79"

[public_config.general]
supervisor_mode = "simple"
validators_count = 2
