[private_config]
consensus_public_key = "eb4a72fab3003b23a605e3a0477c9811271f833dda1b0a8ab9153333ca57ad47"
external_address = "94.174.127.26:6332"
listen_address = "0.0.0.0:6332"
master_key_path = "master.key.toml"

[private_config.api]
private_api_address = "0.0.0.0:9001"
public_api_address = "0.0.0.0:9000"
state_update_timeout = 10000

[private_config.api.server_restart]
max_retries = 20
retry_timeout = 500
[[private_config.connect_list.peers]]
address = "86.190.119.237:6332"
public_key = "61789977e39ceb9b7395f0cdf66e1d26e5c2e78540469d1433fb39702ee00492"

[private_config.database]
compression_type = "none"
create_if_missing = true
[private_config.mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[private_config.mempool.flush_pool_strategy]
timeout = 20
type = "timeout"

[private_config.network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[public_config.consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[[public_config.consensus.validator_keys]]
consensus_key = "61789977e39ceb9b7395f0cdf66e1d26e5c2e78540469d1433fb39702ee00492"
service_key = "c5a6e31ef2eedd2cce287dedded9590eeda7256a1158c35f9770032520cd2b04"

[[public_config.consensus.validator_keys]]
consensus_key = "eb4a72fab3003b23a605e3a0477c9811271f833dda1b0a8ab9153333ca57ad47"
service_key = "ddbb04b53a9626c66dfc16822c55930dfcb4bda010c3987b3125c516b6e8e84a"

[public_config.general]
supervisor_mode = "simple"
validators_count = 2
