[private_config]
consensus_public_key = "02373eac8fc8663f34f1a37224937182208d539dd6aa2c18ec1d3720f0cb296b"
external_address = "0.0.0.0:6332"
listen_address = "0.0.0.0:6332"
master_key_path = "master.key.toml"

[private_config.api]
private_api_address = "0.0.0.0:9001"
public_api_address = "0.0.0.0:9000"
state_update_timeout = 10000

[private_config.api.server_restart]
max_retries = 20
retry_timeout = 500
[[private_config.connect_list.peers]]
address = "0.0.0.0:6333"
public_key = "c13e8b871c67a44a831758b0843b8beb25623506d201cd70fb11054e7d1bf8c9"

[private_config.database]
compression_type = "none"
create_if_missing = true
[private_config.mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[private_config.mempool.flush_pool_strategy]
timeout = 20
type = "timeout"

[private_config.network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[public_config.consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[[public_config.consensus.validator_keys]]
consensus_key = "02373eac8fc8663f34f1a37224937182208d539dd6aa2c18ec1d3720f0cb296b"
service_key = "a1b7cb4a9eab20edb6c6da0d3d543e0451969a4a6efaedff476a07b936a1078c"

[[public_config.consensus.validator_keys]]
consensus_key = "c13e8b871c67a44a831758b0843b8beb25623506d201cd70fb11054e7d1bf8c9"
service_key = "0670ee41f1586d95254543f9b54269c4cfc8a89db8245ca446961450f813d2d4"

[public_config.general]
supervisor_mode = "simple"
validators_count = 2
