address = "127.0.0.1:6331"

[consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[general]
supervisor_mode = "simple"
validators_count = 2

[validator_keys]
consensus_key = "44e6860b6ee1f34ab69e1fd4e425d52c8cabf41378f2d732bfdf4c6df96e8e58"
service_key = "e75a53123250b57e485d46fd2b0ee76d736f12cc135c59031ddb354cab3c41eb"
