address = "127.0.0.1:7091"

[consensus]
first_round_timeout = 3000
max_message_len = 5242880
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[general]
supervisor_mode = "simple"
validators_count = 2

[validator_keys]
consensus_key = "dbb5e6378b572e999709edb4ddde54209681bffc10548f76b7debf7abd9c8658"
service_key = "f261dcc28738a5428cbe313c86ccfd6813ab389ded78aa0b5a9b126d28095ebe"
