# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"]\n\x05Model\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\x13\n\x07weights\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x11\n\tmin_score\x18\x05 \x01(\x02\"5\n\x0eTxShareUpdates\x12\x15\n\tgradients\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x0c\n\x04seed\x18\x02 \x01(\x04\"\x1d\n\rTxSyncBarrier\x12\x0c\n\x04seed\x18\x01 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEL.fields_by_name['weights']._options = None
  _MODEL.fields_by_name['weights']._serialized_options = b'\020\001'
  _TXSHAREUPDATES.fields_by_name['gradients']._options = None
  _TXSHAREUPDATES.fields_by_name['gradients']._serialized_options = b'\020\001'
  _MODEL._serialized_start=17
  _MODEL._serialized_end=110
  _TXSHAREUPDATES._serialized_start=112
  _TXSHAREUPDATES._serialized_end=165
  _TXSYNCBARRIER._serialized_start=167
  _TXSYNCBARRIER._serialized_end=196
# @@protoc_insertion_point(module_scope)
